// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/dht.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node represents a participant in the DHT network
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // 160 bit SHA-1 Hash
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // network address to connect via grpc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_dht_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// PingRequest contains the sender's node info for discovery
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *Node                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"` // node initiating the ping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_dht_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetSender() *Node {
	if x != nil {
		return x.Sender
	}
	return nil
}

// PingResponse contains the reciver's node information
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *Node                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"` // node responding to the ping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_dht_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetSender() *Node {
	if x != nil {
		return x.Sender
	}
	return nil
}

// StoreRequest contains the data to be stored and the sender's info
type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *Node                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"` // the node initiating the request
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_proto_dht_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{3}
}

func (x *StoreRequest) GetSender() *Node {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// StoreResponse confirms whether the storage operation was successfull
type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_dht_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{4}
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// FindNodeRequest asks for nodes mathematically close to a specific target ID
type FindNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *Node                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`                     // node initiating the response
	TargetId      []byte                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 160 bit target ID being searched in the network
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNodeRequest) Reset() {
	*x = FindNodeRequest{}
	mi := &file_proto_dht_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeRequest) ProtoMessage() {}

func (x *FindNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeRequest.ProtoReflect.Descriptor instead.
func (*FindNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{5}
}

func (x *FindNodeRequest) GetSender() *Node {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *FindNodeRequest) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

// FindNodeResponse returns a list of the closes known nodes.
type FindNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // a list of node addresses and Id's closest to the requested target ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNodeResponse) Reset() {
	*x = FindNodeResponse{}
	mi := &file_proto_dht_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeResponse) ProtoMessage() {}

func (x *FindNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeResponse.ProtoReflect.Descriptor instead.
func (*FindNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{6}
}

func (x *FindNodeResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// FindValueRequest asks for the byte value associated with a specific key
type FindValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *Node                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"` // the node initiating the request
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`       // the key for whose value is requested in the network
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindValueRequest) Reset() {
	*x = FindValueRequest{}
	mi := &file_proto_dht_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValueRequest) ProtoMessage() {}

func (x *FindValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValueRequest.ProtoReflect.Descriptor instead.
func (*FindValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{7}
}

func (x *FindValueRequest) GetSender() *Node {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *FindValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// FindValueResponse returns the value if found, or the closest nodes if not
type FindValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`  // the stored data payload for the requested key
	Nodes         []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`  // the closes known nodes for the request key
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"` // to verify which value, if true then value found and value field must be read otherwise nodes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindValueResponse) Reset() {
	*x = FindValueResponse{}
	mi := &file_proto_dht_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValueResponse) ProtoMessage() {}

func (x *FindValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dht_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValueResponse.ProtoReflect.Descriptor instead.
func (*FindValueResponse) Descriptor() ([]byte, []int) {
	return file_proto_dht_proto_rawDescGZIP(), []int{8}
}

func (x *FindValueResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FindValueResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *FindValueResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_proto_dht_proto protoreflect.FileDescriptor

const file_proto_dht_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/dht.proto\x12\x03dht\"5\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\"0\n" +
	"\vPingRequest\x12!\n" +
	"\x06sender\x18\x01 \x01(\v2\t.dht.NodeR\x06sender\"1\n" +
	"\fPingResponse\x12!\n" +
	"\x06sender\x18\x01 \x01(\v2\t.dht.NodeR\x06sender\"Y\n" +
	"\fStoreRequest\x12!\n" +
	"\x06sender\x18\x01 \x01(\v2\t.dht.NodeR\x06sender\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\")\n" +
	"\rStoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x0fFindNodeRequest\x12!\n" +
	"\x06sender\x18\x01 \x01(\v2\t.dht.NodeR\x06sender\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\fR\btargetId\"3\n" +
	"\x10FindNodeResponse\x12\x1f\n" +
	"\x05nodes\x18\x01 \x03(\v2\t.dht.NodeR\x05nodes\"G\n" +
	"\x10FindValueRequest\x12!\n" +
	"\x06sender\x18\x01 \x01(\v2\t.dht.NodeR\x06sender\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"`\n" +
	"\x11FindValueResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1f\n" +
	"\x05nodes\x18\x02 \x03(\v2\t.dht.NodeR\x05nodes\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found2\xd7\x01\n" +
	"\x03DHT\x12+\n" +
	"\x04Ping\x12\x10.dht.PingRequest\x1a\x11.dht.PingResponse\x12.\n" +
	"\x05Store\x12\x11.dht.StoreRequest\x1a\x12.dht.StoreResponse\x127\n" +
	"\bFindNode\x12\x14.dht.FindNodeRequest\x1a\x15.dht.FindNodeResponse\x12:\n" +
	"\tFindValue\x12\x15.dht.FindValueRequest\x1a\x16.dht.FindValueResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_dht_proto_rawDescOnce sync.Once
	file_proto_dht_proto_rawDescData []byte
)

func file_proto_dht_proto_rawDescGZIP() []byte {
	file_proto_dht_proto_rawDescOnce.Do(func() {
		file_proto_dht_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dht_proto_rawDesc), len(file_proto_dht_proto_rawDesc)))
	})
	return file_proto_dht_proto_rawDescData
}

var file_proto_dht_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_dht_proto_goTypes = []any{
	(*Node)(nil),              // 0: dht.Node
	(*PingRequest)(nil),       // 1: dht.PingRequest
	(*PingResponse)(nil),      // 2: dht.PingResponse
	(*StoreRequest)(nil),      // 3: dht.StoreRequest
	(*StoreResponse)(nil),     // 4: dht.StoreResponse
	(*FindNodeRequest)(nil),   // 5: dht.FindNodeRequest
	(*FindNodeResponse)(nil),  // 6: dht.FindNodeResponse
	(*FindValueRequest)(nil),  // 7: dht.FindValueRequest
	(*FindValueResponse)(nil), // 8: dht.FindValueResponse
}
var file_proto_dht_proto_depIdxs = []int32{
	0,  // 0: dht.PingRequest.sender:type_name -> dht.Node
	0,  // 1: dht.PingResponse.sender:type_name -> dht.Node
	0,  // 2: dht.StoreRequest.sender:type_name -> dht.Node
	0,  // 3: dht.FindNodeRequest.sender:type_name -> dht.Node
	0,  // 4: dht.FindNodeResponse.nodes:type_name -> dht.Node
	0,  // 5: dht.FindValueRequest.sender:type_name -> dht.Node
	0,  // 6: dht.FindValueResponse.nodes:type_name -> dht.Node
	1,  // 7: dht.DHT.Ping:input_type -> dht.PingRequest
	3,  // 8: dht.DHT.Store:input_type -> dht.StoreRequest
	5,  // 9: dht.DHT.FindNode:input_type -> dht.FindNodeRequest
	7,  // 10: dht.DHT.FindValue:input_type -> dht.FindValueRequest
	2,  // 11: dht.DHT.Ping:output_type -> dht.PingResponse
	4,  // 12: dht.DHT.Store:output_type -> dht.StoreResponse
	6,  // 13: dht.DHT.FindNode:output_type -> dht.FindNodeResponse
	8,  // 14: dht.DHT.FindValue:output_type -> dht.FindValueResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_dht_proto_init() }
func file_proto_dht_proto_init() {
	if File_proto_dht_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dht_proto_rawDesc), len(file_proto_dht_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dht_proto_goTypes,
		DependencyIndexes: file_proto_dht_proto_depIdxs,
		MessageInfos:      file_proto_dht_proto_msgTypes,
	}.Build()
	File_proto_dht_proto = out.File
	file_proto_dht_proto_goTypes = nil
	file_proto_dht_proto_depIdxs = nil
}
